FROM public.ecr.aws/docker/library/node:20-alpine AS build
WORKDIR /app
RUN apk update && apk upgrade --no-cache && \
    apk add --no-cache openssl>=3.5.5-r0
COPY package.json ./
RUN npm install --production=false
COPY . .
RUN npx nest build product

FROM public.ecr.aws/docker/library/node:20-alpine
WORKDIR /app
RUN apk update && apk upgrade --no-cache && \
    apk add --no-cache openssl>=3.5.5-r0
COPY package.json ./
RUN npm install --production=true && npm cache clean --force
COPY --from=build /app/dist ./dist
COPY --from=build /app/libs ./libs
EXPOSE 3010
CMD ["node", "dist/microservices/product/main"]
